
const RC={
  leg:'linear-gradient(135deg,#f59e0b,#fcd34d)',
  ultra:'linear-gradient(135deg,#ff5fa0,#ffb3d8)',
  rare:'linear-gradient(135deg,#38bdf8,#bae6fd)',
  uncommon:'linear-gradient(135deg,#22d3a0,#a7f3d0)',
  common:'linear-gradient(135deg,#d1d5db,#f3f4f6)',
  exotic:'linear-gradient(135deg,#ff64dc,#b06aff,#7b9fff)',
  item:'linear-gradient(135deg,#b06aff,#d9b3ff)',
};
const RL={leg:"Legendary",ultra:"Ultra-Rare",rare:"Rare",uncommon:"Uncommon",common:"Common",exotic:"Exotic",item:"Item"};

// ══════════════════════════════════════════════════════════
//  FAIRYVALUE — Liste des pets & valeurs 2026
//  v  = valeur actuelle   ov = ancienne valeur
//  hot = très demandé en ce moment
// ══════════════════════════════════════════════════════════
const PETS = [

  // ════ LEGENDARY ════
  {n:"Bat Dragon",                   v:590,  ov:560,  r:"leg", hot:true},
  {n:"Shadow Dragon",                v:510,  ov:470,  r:"leg", hot:true},
  {n:"Giraffe",                      v:265,  ov:230,  r:"leg", hot:true},
  {n:"Frost Dragon",                 v:212,  ov:200,  r:"leg"},
  {n:"Owl",                          v:170,  ov:165,  r:"leg"},
  {n:"Parrot",                       v:133,  ov:130,  r:"leg"},
  {n:"Crow",                         v:113,  ov:110,  r:"leg"},
  {n:"African Wild Dog",             v:95,   ov:88,   r:"ultra", hot:true},
  {n:"Giant Panda",                  v:59,   ov:90,   r:"exotic"},
  {n:"Balloon Unicorn",              v:65,   ov:87,   r:"leg"},
  {n:"Evil Unicorn",                 v:109,  ov:87,   r:"leg"},
  {n:"Cryptid",                      v:71,   ov:65,   r:"leg"},
  {n:"Hedgehog",                     v:54,   ov:52,   r:"ultra"},
  {n:"Blazing Lion",                 v:47,   ov:44,   r:"exotic", hot:true},
  {n:"Diamond Butterfly",            v:47,   ov:44,   r:"exotic"},
  {n:"Dalmatian",                    v:44,   ov:42,   r:"ultra"},
  {n:"Haetae",                       v:42,   ov:40,   r:"exotic", hot:true},
  {n:"Orchid Butterfly",             v:40,   ov:38,   r:"exotic"},
  {n:"Arctic Reindeer",              v:40,   ov:38,   r:"leg"},
  {n:"Velocirooster",                v:35,   ov:33,   r:"exotic", hot:true},
  {n:"Silverback Gorilla",           v:33,   ov:31,   r:"exotic"},
  {n:"Pelican",                      v:25,   ov:23,   r:"ultra"},
  {n:"Cow",                          v:24,   ov:22,   r:"rare", hot:true},
  {n:"Mini Pig",                     v:23,   ov:21,   r:"rare"},
  {n:"Strawberry Bat Dragon",        v:22,   ov:20,   r:"exotic"},
  {n:"Turtle",                       v:21,   ov:19,   r:"leg"},
  {n:"Peppermint Penguin",           v:21,   ov:19,   r:"ultra"},
  {n:"Chocolate Chip Bat Dragon",    v:19,   ov:18,   r:"exotic"},
  {n:"Monkey King",                  v:19,   ov:18,   r:"exotic"},
  {n:"Hot Doggo",                    v:18,   ov:17,   r:"exotic"},
  {n:"Flamingo",                     v:18,   ov:17,   r:"ultra"},
  {n:"Gumball Caterpillar",          v:18,   ov:17,   r:"exotic"},
  {n:"Kangaroo",                     v:15,   ov:14,   r:"leg"},
  {n:"Cabbit",                       v:15,   ov:14,   r:"exotic"},
  {n:"Elephant",                     v:15,   ov:14,   r:"rare"},
  {n:"Goose",                        v:14,   ov:13,   r:"exotic"},
  {n:"Albino Monkey",                v:15,   ov:14,   r:"leg"},
  {n:"Caterpillar",                  v:14,   ov:13,   r:"ultra"},
  {n:"Candyfloss Chick",             v:13,   ov:12,   r:"exotic", hot:true},
  {n:"Mermicorn",                    v:13,   ov:12,   r:"exotic"},
  {n:"Crocodile",                    v:12,   ov:11,   r:"ultra"},
  {n:"Sugar Glider",                 v:12,   ov:11,   r:"leg"},
  {n:"Blue Dog",                     v:12,   ov:12,   r:"uncommon", hot:true},
  {n:"Jekyll Hydra",                 v:11,   ov:10,   r:"exotic"},
  {n:"Lion",                         v:11,   ov:10,   r:"exotic"},
  {n:"Candicorn",                    v:11,   ov:10,   r:"exotic"},
  {n:"Border Collie",                v:10,   ov:10,   r:"ultra"},
  {n:"Fairy Bat Dragon",             v:9,    ov:8,    r:"exotic"},
  {n:"Undead Jousting Horse",        v:10,   ov:9,    r:"exotic"},
  {n:"Dragonfruit Fox",              v:9,    ov:8,    r:"exotic", hot:true},
  {n:"Winged Tiger",                 v:8,    ov:8,    r:"exotic"},
  {n:"Cupid Dragon",                 v:8,    ov:7,    r:"exotic"},
  {n:"Frost Unicorn",                v:8,    ov:7,    r:"exotic"},
  {n:"Goat",                         v:8,    ov:7,    r:"ultra"},
  {n:"Bush Elephant",                v:7,    ov:7,    r:"ultra"},
  {n:"Alpaca",                       v:7,    ov:7,    r:"ultra"},
  {n:"Field Mouse",                  v:7,    ov:6,    r:"ultra"},
  {n:"Strawberry Penguin",           v:7,    ov:6,    r:"ultra", hot:true},
  {n:"Irish Water Spaniel",          v:7,    ov:6,    r:"ultra"},
  {n:"Lion Cub",                     v:7,    ov:6,    r:"ultra"},
  {n:"Papa Moose",                   v:7,    ov:6,    r:"ultra"},
  {n:"Dango Penguins",               v:7,    ov:6,    r:"ultra"},
  {n:"Frostbite Bear",               v:6,    ov:6,    r:"ultra"},
  {n:"Black-Chested Pheasant",       v:6,    ov:5,    r:"ultra"},
  {n:"Owlbear",                      v:6,    ov:5,    r:"ultra"},
  {n:"Shark Puppy",                  v:6,    ov:5,    r:"ultra"},
  {n:"Siamese Cat",                  v:6,    ov:5,    r:"ultra"},
  {n:"Pig",                          v:6,    ov:5,    r:"rare"},
  {n:"Tio De Nadal",                 v:5,    ov:5,    r:"ultra"},
  {n:"Pirate Ghost Capuchin Monkey", v:5,    ov:5,    r:"exotic"},
  {n:"Moose Calf",                   v:5,    ov:5,    r:"ultra"},
  {n:"Arctic Fox",                   v:5,    ov:5,    r:"uncommon"},
  {n:"Frost Fury",                   v:5,    ov:5,    r:"leg"},
  {n:"Pineapple Owl",                v:5,    ov:5,    r:"ultra"},
  {n:"Sheeeeep",                     v:5,    ov:5,    r:"ultra"},
  {n:"Jellyfish",                    v:5,    ov:5,    r:"ultra"},
  {n:"Royal Mistletroll",            v:5,    ov:5,    r:"exotic"},
  {n:"Rose Dragon",                  v:5,    ov:5,    r:"exotic"},
  {n:"Vampire Dragon",               v:5,    ov:5,    r:"exotic"},
  {n:"Grim Dragon",                  v:5,    ov:5,    r:"exotic"},
  {n:"Meerkat",                      v:5,    ov:5,    r:"ultra"},
  {n:"Shrew",                        v:5,    ov:4,    r:"ultra"},
  {n:"Pink Cat",                     v:5,    ov:5,    r:"uncommon", hot:true},
  {n:"Hare",                         v:5,    ov:4,    r:"uncommon"},
  {n:"Fallow Deer",                  v:4,    ov:4,    r:"uncommon"},
  {n:"Nessie",                       v:4,    ov:4,    r:"leg"},
  {n:"Many Mackerel",                v:4,    ov:4,    r:"ultra"},
  {n:"Caelum Cervi",                 v:4,    ov:4,    r:"leg"},
  {n:"Werewolf",                     v:4,    ov:4,    r:"uncommon"},
  {n:"Tortuga de la Isla",           v:4,    ov:4,    r:"leg"},
  {n:"Ring-tailed Lemur",            v:4,    ov:4,    r:"ultra"},
  {n:"Mechapup",                     v:4,    ov:4,    r:"ultra"},
  {n:"Sugar Axolotl",                v:4,    ov:4,    r:"ultra"},
  {n:"Lava Dragon",                  v:4,    ov:3,    r:"exotic"},
  {n:"Zombie Buffalo",               v:4,    ov:4,    r:"ultra"},
  {n:"Puffin",                       v:4,    ov:4,    r:"ultra"},
  {n:"Sea Slug",                     v:4,    ov:4,    r:"ultra"},
  {n:"Brown Bear",                   v:4,    ov:4,    r:"ultra"},
  {n:"Polar Bear",                   v:4,    ov:4,    r:"ultra"},
  {n:"Diamond Amazon",               v:4,    ov:4,    r:"exotic"},
  {n:"Sakura Spirit",                v:4,    ov:3,    r:"exotic"},
  {n:"Phantom Dragon",               v:3,    ov:3,    r:"exotic"},
  {n:"Alley Cat",                    v:4,    ov:3,    r:"ultra"},
  {n:"Groundhog",                    v:4,    ov:3,    r:"uncommon"},
  {n:"Bald Eagle",                   v:4,    ov:3,    r:"uncommon"},
  {n:"Platypus",                     v:4,    ov:3,    r:"ultra"},
  {n:"Hyena",                        v:4,    ov:3,    r:"ultra"},
  {n:"Emperor Gorilla",              v:3,    ov:3,    r:"ultra"},
  {n:"Glacier Kitsune",              v:3,    ov:3,    r:"exotic"},
  {n:"Purple Butterfly",             v:3,    ov:3,    r:"ultra"},
  {n:"Glacier Moth",                 v:3,    ov:3,    r:"ultra"},
  {n:"Honey Badger",                 v:3,    ov:3,    r:"ultra"},
  {n:"Arctic Dusk Dragon",           v:3,    ov:3,    r:"exotic"},
  {n:"Halloween White Ghost Dragon", v:3,    ov:3,    r:"exotic"},
  {n:"Midnight Dragon",              v:3,    ov:3,    r:"exotic"},
  {n:"Aurora Fox",                   v:3,    ov:3,    r:"ultra"},
  {n:"Happy Clam",                   v:3,    ov:3,    r:"ultra"},
  {n:"Giant Anteater",               v:3,    ov:3,    r:"ultra"},
  {n:"Giant Gold Scarab",            v:3,    ov:3,    r:"ultra"},
  {n:"Diamond Albatross",            v:3,    ov:3,    r:"exotic"},
  {n:"Christmas Pudding Pup",        v:3,    ov:3,    r:"ultra"},
  {n:"Tri-horned Treehopper",        v:3,    ov:3,    r:"ultra"},
  {n:"Munchkin Cat",                 v:3,    ov:3,    r:"ultra"},
  {n:"Dancing Dragon",               v:2,    ov:2,    r:"exotic"},
  {n:"2D Kitty",                     v:2,    ov:2,    r:"exotic"},
  {n:"Kookaburra",                   v:2,    ov:2,    r:"ultra"},
  {n:"Unicorn",                      v:2,    ov:2,    r:"leg"},
  {n:"Diamond Hamster",              v:2,    ov:2,    r:"ultra"},
  {n:"Flaming Fox",                  v:2,    ov:2,    r:"ultra"},
  {n:"Golden Chow-Chow",             v:2,    ov:2,    r:"ultra"},
  {n:"Majestic Pony",                v:2,    ov:2,    r:"leg"},
  {n:"Frost Phoenix",                v:2,    ov:2,    r:"leg"},
  {n:"Llama",                        v:2,    ov:2,    r:"ultra"},
  {n:"Turkey",                       v:2,    ov:2,    r:"uncommon"},
  {n:"Wood Pigeon",                  v:2,    ov:2,    r:"uncommon"},
  {n:"Slime",                        v:2,    ov:2,    r:"uncommon"},
  {n:"Ice Golem",                    v:2,    ov:2,    r:"exotic"},
  {n:"Lavender Dragon",              v:2,    ov:2,    r:"exotic"},
  {n:"Ice Wolf",                     v:2,    ov:2,    r:"uncommon"},
  {n:"Husky",                        v:2,    ov:2,    r:"uncommon"},
  {n:"Diamond Ladybug",              v:1.75, ov:1.5,  r:"exotic"},
  {n:"Diamond King Penguin",         v:1.75, ov:1.5,  r:"exotic"},
  {n:"Glormy Leo",                   v:1.75, ov:1.5,  r:"exotic"},
  {n:"Emberlight",                   v:1.75, ov:1.5,  r:"exotic"},
  {n:"Vanilla Penguin",              v:1.75, ov:1.5,  r:"ultra"},
  {n:"Lamb",                         v:1.75, ov:1.5,  r:"ultra"},
  {n:"Ice Cream Hermit Crab",        v:1.75, ov:1.5,  r:"ultra"},
  {n:"Wild Boar",                    v:1.75, ov:1.5,  r:"uncommon"},
  {n:"Swan",                         v:1.75, ov:1.5,  r:"ultra"},
  {n:"Queen Bee",                    v:1.5,  ov:1.5,  r:"rare"},
  {n:"Candy Hare",                   v:1.5,  ov:1.5,  r:"uncommon"},
  {n:"Peach Owl",                    v:1.5,  ov:1.5,  r:"ultra"},
  {n:"Apple Owl",                    v:1.5,  ov:1.5,  r:"ultra"},
  {n:"Ram",                          v:1.5,  ov:1.5,  r:"uncommon"},
  {n:"German Shepherd",              v:1.5,  ov:1.5,  r:"uncommon"},
  {n:"Glormy Hound",                 v:1.25, ov:1.25, r:"exotic"},
  {n:"Phoenix",                      v:1.25, ov:1.25, r:"exotic"},
  {n:"Leviathan",                    v:1.25, ov:1.25, r:"exotic"},
  {n:"Axolotl",                      v:1.15, ov:1.15, r:"uncommon"},
  {n:"Rainbow Dragon",               v:1.15, ov:1.15, r:"exotic"},
  {n:"Cheetah",                      v:1.15, ov:1.15, r:"uncommon"},
  {n:"Capybara",                     v:1.35, ov:1.35, r:"uncommon"},
  {n:"Black Panther",                v:1.35, ov:1.35, r:"rare"},
  {n:"Dodo",                         v:1,    ov:1,    r:"rare"},
  {n:"T-Rex",                        v:1,    ov:1,    r:"rare"},
  {n:"Shark",                        v:1,    ov:1,    r:"rare"},
  {n:"Dragon",                       v:0.45, ov:0.45, r:"leg"},
  {n:"Drake",                        v:1.15, ov:1.15, r:"uncommon"},
  {n:"Panda",                        v:0.42, ov:0.42, r:"rare"},
  {n:"Griffin",                      v:0.4,  ov:0.4,  r:"leg"},
  {n:"Cerberus",                     v:0.9,  ov:0.9,  r:"leg"},
  {n:"Goldhorn",                     v:0.85, ov:0.85, r:"leg"},
  {n:"Kitsune",                      v:0.5,  ov:0.5,  r:"leg"},
  {n:"Cobra",                        v:0.5,  ov:0.5,  r:"leg"},
  {n:"Diamond Dragon",               v:0.75, ov:0.75, r:"leg"},
  {n:"Golden Unicorn",               v:0.75, ov:0.75, r:"leg"},
  {n:"Snow Owl",                     v:0.75, ov:0.75, r:"leg"},
  {n:"Golden Ladybug",               v:0.75, ov:0.75, r:"leg"},
  {n:"Golden Dragon",                v:0.55, ov:0.55, r:"leg"},
  {n:"Robo Dog",                     v:0.6,  ov:0.6,  r:"leg"},
  {n:"Diamond Griffin",              v:0.7,  ov:0.7,  r:"leg"},
  {n:"Golden Griffin",               v:0.4,  ov:0.4,  r:"leg"},
  {n:"Diamond Unicorn",              v:1,    ov:1,    r:"exotic"},
  {n:"Reindeer",                     v:0.8,  ov:0.8,  r:"uncommon"},
  {n:"Rhino",                        v:1.5,  ov:1.5,  r:"rare"},
  {n:"Silly Duck",                   v:1.5,  ov:1.5,  r:"rare"},
  {n:"Skele-Rex",                    v:1.25, ov:1.25, r:"rare"},
  {n:"Harp Seal",                    v:1.15, ov:1.15, r:"uncommon"},
  {n:"Penguin",                      v:0.5,  ov:0.5,  r:"uncommon"},
  {n:"Horse",                        v:0.38, ov:0.38, r:"uncommon"},
  {n:"Pomeranian",                   v:0.38, ov:0.38, r:"uncommon"},

  // ── Pets manquants ──
  {n:"Green Butterfly",              v:1.35, ov:1.35, r:"ultra"},
  {n:"Tree Kangaroo",                v:1.35, ov:1.35, r:"ultra"},
  {n:"Albino Gorilla",               v:1.35, ov:1.35, r:"ultra"},
  {n:"Ninja Monkey",                 v:1.25, ov:1.25, r:"ultra"},
  {n:"Ghost Dog",                    v:0.7,  ov:0.7,  r:"uncommon"},
  {n:"Evil Rock",                    v:0.7,  ov:0.7,  r:"uncommon"},
  {n:"Business Monkey",              v:0.6,  ov:0.6,  r:"ultra"},
  {n:"Royal Palace Spaniel",         v:0.6,  ov:0.6,  r:"ultra"},
  {n:"Binturong",                    v:0.6,  ov:0.6,  r:"ultra"},
  {n:"Lynx",                         v:0.65, ov:0.65, r:"rare"},
  {n:"Kiwi",                         v:0.65, ov:0.65, r:"uncommon"},
  {n:"English Sheepdog",             v:0.65, ov:0.65, r:"uncommon"},
  {n:"Great Pyrenees",               v:0.65, ov:0.65, r:"uncommon"},
  {n:"Ancient Dragon",               v:0.4,  ov:0.4,  r:"exotic"},
  {n:"Villain Gibbon",               v:0.4,  ov:0.4,  r:"exotic"},
  {n:"Wooly Rhino",                  v:0.5,  ov:0.5,  r:"uncommon"},
  {n:"Frostbite Cub",                v:0.5,  ov:0.5,  r:"ultra"},
  {n:"Lunar Moon Bear",              v:0.35, ov:0.35, r:"exotic"},
  {n:"Brown Springer Spaniel",       v:0.45, ov:0.45, r:"uncommon"},
  {n:"Black Springer Spaniel",       v:0.45, ov:0.45, r:"uncommon"},
  {n:"Mr Whiskerpips",               v:0.45, ov:0.45, r:"ultra"},
  {n:"Dragonfly",                    v:0.3,  ov:0.3,  r:"uncommon"},
  {n:"Glormy Dolphin",               v:0.3,  ov:0.3,  r:"exotic"},
  {n:"Temple Friend",                v:0.3,  ov:0.3,  r:"uncommon"},
  {n:"Quetzalcoatl",                 v:0.3,  ov:0.3,  r:"exotic"},
  {n:"Slimingo",                     v:0.3,  ov:0.3,  r:"uncommon"},
  {n:"Christmas Spirit",             v:0.3,  ov:0.3,  r:"uncommon"},
  {n:"Fire Stallion",                v:0.3,  ov:0.3,  r:"uncommon"},
  {n:"Giant Blue Scarab",            v:0.42, ov:0.42, r:"ultra"},
  {n:"Nautilus",                     v:0.42, ov:0.42, r:"ultra"},
  {n:"Irish Elk",                    v:0.5,  ov:0.5,  r:"uncommon"},
  {n:"Happy Duckling",               v:0.5,  ov:0.5,  r:"uncommon"},
  {n:"Zombie Wolf",                  v:0.4,  ov:0.4,  r:"uncommon"},
  {n:"Blue Ringed Octopus",          v:0.4,  ov:0.4,  r:"ultra"},
  {n:"Pretty Pony",                  v:0.4,  ov:0.4,  r:"uncommon"},
  {n:"Lunar Gold Tiger",             v:0.25, ov:0.25, r:"exotic"},
  {n:"French Bulldog",               v:0.85, ov:0.85, r:"uncommon"},
  {n:"Maneki-Neko",                  v:0.6,  ov:0.6,  r:"exotic"},
  {n:"Dire Stag",                    v:0.6,  ov:0.6,  r:"exotic"},
  {n:"Golden Hummingbird",           v:0.6,  ov:0.6,  r:"exotic"},
  {n:"Sunglider",                    v:0.6,  ov:0.6,  r:"exotic"},
  {n:"Blue Whale",                   v:0.6,  ov:0.6,  r:"ultra"},
  {n:"Alicorn",                      v:0.55, ov:0.55, r:"exotic"},
  {n:"Ice Moth Dragon",              v:0.55, ov:0.55, r:"exotic"},
  {n:"Kitty Bat",                    v:0.55, ov:0.55, r:"exotic"},
  {n:"Yeti",                         v:0.65, ov:0.65, r:"uncommon"},
  {n:"Puffer Fish",                  v:0.65, ov:0.65, r:"ultra"},
  {n:"Halloween Golden Mummy Cat",   v:0.5,  ov:0.5,  r:"ultra"},
  {n:"Scarecrow Crow",               v:0.5,  ov:0.5,  r:"ultra"},
  {n:"Mecha Meow",                   v:0.5,  ov:0.5,  r:"exotic"},
  {n:"Diamond Mahi Mahi",            v:0.5,  ov:0.5,  r:"exotic"},
  {n:"Striped Eggy",                 v:0.5,  ov:0.5,  r:"exotic"},
  {n:"Rosy Maple Moth",              v:0.5,  ov:0.5,  r:"exotic"},
  {n:"Blue Betta Fish",              v:0.5,  ov:0.5,  r:"exotic"},
  {n:"Kraken",                       v:0.5,  ov:0.5,  r:"exotic"},
  {n:"Evil Chick",                   v:0.5,  ov:0.5,  r:"exotic"},
  {n:"Frostclaw",                    v:0.5,  ov:0.5,  r:"exotic"},
  {n:"Dimension Drifter",            v:0.5,  ov:0.5,  r:"exotic"},
  {n:"Super Saru",                   v:0.5,  ov:0.5,  r:"exotic"},
  {n:"Primal Kaijunior",             v:0.5,  ov:0.5,  r:"exotic"},
  {n:"Scorching Kaijunior",          v:1.15, ov:1.15, r:"exotic"},
  {n:"Hero Gibbon",                  v:1.15, ov:1.15, r:"exotic"},
  {n:"Bunny Swirl",                  v:0.8,  ov:0.8,  r:"ultra"},
  {n:"Baku",                         v:0.65, ov:0.65, r:"exotic"},
  {n:"Chimera",                      v:0.65, ov:0.65, r:"exotic"},
  {n:"Billy Goat",                   v:0.65, ov:0.65, r:"uncommon"},
  {n:"Fleur De Ice",                 v:0.65, ov:0.65, r:"exotic"},
  {n:"Princess Capuchin Monkey",     v:0.65, ov:0.65, r:"exotic"},
  {n:"Scarebear",                    v:0.65, ov:0.65, r:"exotic"},
  {n:"Berry Cool Cube",              v:0.65, ov:0.65, r:"uncommon"},
  {n:"Winter Buck",                  v:0.65, ov:0.65, r:"exotic"},
  {n:"Sea Turtle",                   v:0.65, ov:0.65, r:"exotic"},
  {n:"Squid",                        v:0.75, ov:0.75, r:"ultra"},
  {n:"Chameleon",                    v:0.75, ov:0.75, r:"ultra"},
  {n:"Golden Albatross",             v:0.75, ov:0.75, r:"exotic"},
  {n:"Chocolate Chow-Chow",          v:0.75, ov:0.75, r:"ultra"},
  {n:"Black Chow-Chow",              v:0.75, ov:0.75, r:"ultra"},
  {n:"Green-Chested Pheasant",       v:0.75, ov:0.75, r:"ultra"},
  {n:"Lava Wolf",                    v:0.75, ov:0.75, r:"exotic"},
  {n:"Shetland Pony",                v:0.75, ov:0.75, r:"uncommon"},
  {n:"Sunrise Duckling",             v:0.75, ov:0.75, r:"ultra"},
  {n:"Criosphinx",                   v:0.75, ov:0.75, r:"exotic"},
  {n:"Dimorphodon",                  v:0.75, ov:0.75, r:"ultra"},
  {n:"Guardian Lion",                v:0.7,  ov:0.7,  r:"exotic"},
  {n:"Hawk",                         v:0.7,  ov:0.7,  r:"uncommon"},
  {n:"Mushroom Friend",              v:0.7,  ov:0.7,  r:"uncommon"},
  {n:"Gilded Snake",                 v:0.7,  ov:0.7,  r:"ultra"},
  {n:"Influencer Gibbon",            v:0.7,  ov:0.7,  r:"exotic"},
  {n:"Priceless Shrimp",             v:0.7,  ov:0.7,  r:"ultra"},
  {n:"Fire Mare",                    v:0.7,  ov:0.7,  r:"ultra"},
  {n:"Snowball Pet",                 v:0.8,  ov:0.8,  r:"uncommon"},
  {n:"King Bee",                     v:0.75, ov:0.75, r:"ultra"},
  {n:"Royal Corgi",                  v:1.15, ov:1.15, r:"ultra"},
  {n:"Golden Rat",                   v:1,    ov:1,    r:"ultra"},
  {n:"White Amazon",                 v:1,    ov:1,    r:"ultra"},
  {n:"Fir
